<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.536">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xinrui Xiong 806329308">
<meta name="dcterms.date" content="2024-02-20">

<title>Biostat 212A Homework 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw3_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw3_files/libs/quarto-html/quarto.js"></script>
<script src="hw3_files/libs/quarto-html/popper.min.js"></script>
<script src="hw3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw3_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostat 212A Homework 3</h1>
<p class="subtitle lead">Due Feb 20, 2024 @ 11:59PM</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xinrui Xiong 806329308 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 20, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="isl-exercise-5.4.2-10pts" class="level2">
<h2 class="anchored" data-anchor-id="isl-exercise-5.4.2-10pts">ISL Exercise 5.4.2 (10pts)</h2>
<p>We will now derive the probability that a given observation is part of a bootstrap sample. Suppose that we obtain a bootstrap sample from a set of n observations.</p>
<p>(a) What is the probability that the first bootstrap observation is not the jth observation from the original sample? Justify your answer.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Since the bootstrap sample is a replacement of original dataset, the probability of selecting one specific observation is <span class="math inline">\(\frac{1}{n}\)</span> , and the probability of not selecting one specific observation (<span class="math inline">\(j_{th}\)</span>) is <span class="math inline">\(1-\frac{1}{n}=\frac{n-1}{n}\)</span>.</p>
</font><p><font color="Blue"></font></p>
<p>(b) What is the probability that the second bootstrap observation is not the jth observation from the original sample?</p>
<p><font color="Blue"></font></p><font color="Blue">
<p><span class="math inline">\({(1-\frac{1}{n})}\)</span>. The result remains because the bootstrap sample is a replacement of original dataset, and each of the replacement is independent, so the probability remains.</p>
</font><p><font color="Blue"></font></p>
<p>(c) Argue that the probability that the jth observation is not in the bootstrap sample is <span class="math inline">\((1 − 1/n)^n\)</span>.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>For n observations in the bootstrap sample, the probability that each one isn’t the <span class="math inline">\(j_{th}\)</span> in that set is <span class="math inline">\((1 − 1/n)\)</span>, so the probability is <span class="math inline">\((1 − 1/n)^n\)</span>.</p>
</font><p><font color="Blue"></font></p>
<p>(d) When n = 5, what is the probability that the jth observation is in the bootstrap sample?</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Substitute the n=5, we have</p>
<p><span class="math display">\[
P(j_{th}\ not\ in\ bootstrap)=(1 − 1/5)^5= 0.32768,
\]</span></p>
<p>so,</p>
<p><span class="math display">\[
P(j_{th}\ in\ bootstrap)=1-0.327681-0.32768=0.67232.
\]</span></p>
</font><p><font color="Blue"></font></p>
<p>(e) When n = 100, what is the probability that the jth observation is in the bootstrap sample?</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Based on the same calculation as in (d), we have</p>
<p><span class="math display">\[
P(j_{th}\ in\ bootstrap)=1-(1 − 1/100)^{100}=0.6339677
\]</span></p>
</font><p><font color="Blue"></font></p>
<p>(f) When n = 10, 000, what is the probability that the jth observation is in the bootstrap sample?</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Based on the same calculation as in (d), we have</p>
<p><span class="math display">\[
P(j_{th}\ in\ bootstrap)=1-(1 − 1/10000)^{10000}=0.632139
\]</span></p>
</font><p><font color="Blue"></font></p>
<p>(g) Create a plot that displays, for each integer value of n from 1 to 100,000, the probability that the jth observation is in the bootstrap sample. Comment on what you observe.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>We can use ggplot() to construct the plot：</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>X<span class="ot">=</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100000</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">=</span><span class="dv">1</span><span class="sc">-</span>(<span class="dv">1-1</span><span class="sc">/</span>X)<span class="sc">^</span>X</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df<span class="ot">&lt;-</span><span class="fu">data.frame</span>(X,Y)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> X, <span class="at">y =</span> Y)) <span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"integer value of n"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"probability"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"The probability that the jth observation is in the bootstrap sample"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fl">0.5</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the plot, we can see the probability soon converge to a number between 0.6 and 0.65 with the increasing of n.</p>
</font><p><font color="Blue"></font></p>
<p>(h) We will now investigate numerically the probability that a bootstrap sample of size n = 100 contains the jth observation. Here j = 4. We repeatedly create bootstrap samples, and each time we record whether or not the fourth observation is contained in the bootstrap sample.</p>
<blockquote class="blockquote">
<p>&gt; store &lt;- rep(NA, 10000)</p>
<p>&gt; for(i in 1:10000){</p>
<p>store[i] &lt;- sum(sample(1:100, rep=TRUE) == 4) &gt; 0</p>
<p>}</p>
<p>&gt; mean(store)</p>
</blockquote>
<p>Comment on the results obtained.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Run the codes above:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>store <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10000</span>) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>){ </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    store[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, <span class="at">rep=</span><span class="cn">TRUE</span>) <span class="sc">==</span> <span class="dv">4</span>) <span class="sc">&gt;</span> <span class="dv">0</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(store)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6337</code></pre>
</div>
</div>
<p>This is consistent with the well-known mathematical formula</p>
<p><span class="math display">\[
\lim_{x \to \infty}{(1-1/x)^{x}}=\frac{1}{e}
\]</span></p>
<p>so the probability will converge to <span class="math inline">\(1-\frac{1}{e}= 0.6321206\)</span> with the n keeping increasing.</p>
</font><p><font color="Blue"></font></p>
</section>
<section id="isl-exercise-5.4.9-20pts" class="level2">
<h2 class="anchored" data-anchor-id="isl-exercise-5.4.9-20pts">ISL Exercise 5.4.9 (20pts)</h2>
<p>We will now consider the Boston housing data set, from the ISLR2 library.</p>
<p>(a) Based on this data set, provide an estimate for the population mean of medv. Call this estimate <span class="math inline">\(\hat \mu\)</span>.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>We use sample mean to estimate population mean:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>mu_hat<span class="ot">&lt;-</span><span class="fu">mean</span>(Boston<span class="sc">$</span>medv)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>mu_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.53281</code></pre>
</div>
</div>
</font><p><font color="Blue"></font></p>
<p>(b) Provide an estimate of the standard error of <span class="math inline">\(\hat \mu\)</span>. Interpret this result.</p>
<p>Hint: We can compute the standard error of the sample mean by dividing the sample standard deviation by the square root of the number of observations.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>We use sample mean to estimate population mean:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sd_mu_hat<span class="ot">&lt;-</span><span class="fu">sd</span>(Boston<span class="sc">$</span>medv)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(Boston<span class="sc">$</span>medv))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>sd_mu_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4088611</code></pre>
</div>
</div>
</font><p><font color="Blue"></font></p>
<p>(c) Now estimate the standard error of <span class="math inline">\(\hat \mu\)</span> using the bootstrap. How does this compare to your answer from (b)?</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>We use boot() function in “boot” package to calculate it:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>get_mean<span class="ot">&lt;-</span><span class="cf">function</span>(d,i){</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(d[i])</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>boot_results<span class="ot">&lt;-</span><span class="fu">boot</span>(Boston<span class="sc">$</span>medv, get_mean, <span class="at">R=</span><span class="dv">10000</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>boot_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston$medv, statistic = get_mean, R = 10000)


Bootstrap Statistics :
    original       bias    std. error
t1* 22.53281 -0.003155573    0.407378</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>boot_sd<span class="ot">&lt;-</span><span class="fu">sd</span>(boot_results<span class="sc">$</span>t)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>boot_sd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.407378</code></pre>
</div>
</div>
<p>As we can see, the standard error is very closer to the estimate standard error in (b).</p>
</font><p><font color="Blue"></font></p>
<p>(d) Based on your bootstrap estimate from (c), provide a 95 % confidence interval for the mean of medv. Compare it to the results obtained using t.test(Boston$medv).</p>
<p>Hint: You can approximate a 95 % confidence interval using the formula <span class="math inline">\([\hat \mu-2SE(\hat \mu),\hat \mu+2SE(\hat \mu)]\)</span>.</p>
<p><font color="Blue"></font></p><font color="Blue">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t test results</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>t_results<span class="ot">&lt;-</span><span class="fu">t.test</span>(Boston<span class="sc">$</span>medv)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>t_results<span class="sc">$</span>conf.int[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.72953 23.33608</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculated results</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>c_results<span class="ot">&lt;-</span><span class="fu">c</span>(mu_hat<span class="dv">-2</span><span class="sc">*</span>boot_sd,mu_hat<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>boot_sd)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>c_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.71805 23.34756</code></pre>
</div>
</div>
<p>The confidence intervals results are almost the same.</p>
</font><p><font color="Blue"></font></p>
<p>(e) Based on this data set, provide an estimate, <span class="math inline">\(\hat \mu_{med}\)</span>, for the median value of medv in the population.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>We use median() to get the sample median, as the estimation of the median value of medv in the population.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mu_hat_med<span class="ot">&lt;-</span><span class="fu">median</span>(Boston<span class="sc">$</span>medv)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>mu_hat_med</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.2</code></pre>
</div>
</div>
</font><p><font color="Blue"></font></p>
<p>(f) We now would like to estimate the standard error of <span class="math inline">\(\hat \mu_{med}\)</span>. Unfortunately, there is no simple formula for computing the standard error of the median. Instead, estimate the standard error of the median using the bootstrap. Comment on your findings.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>The calculation is the same as (c), we just need to replace the statistical function mean() with median().</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>get_median<span class="ot">&lt;-</span><span class="cf">function</span>(d,i){</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">median</span>(d[i])</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>boot_results1<span class="ot">&lt;-</span><span class="fu">boot</span>(Boston<span class="sc">$</span>medv, get_median, <span class="at">R=</span><span class="dv">10000</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>boot_results1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston$medv, statistic = get_median, R = 10000)


Bootstrap Statistics :
    original   bias    std. error
t1*     21.2 -0.00392   0.3776492</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>boot_sd1<span class="ot">&lt;-</span><span class="fu">sd</span>(boot_results1<span class="sc">$</span>t)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>boot_sd1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3776492</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate median</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(boot_results1<span class="sc">$</span>t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.2</code></pre>
</div>
</div>
<p>As we can see, the std.error is 0.3813532. The estimate median is 21.2(<strong>median(boot_results1$t)</strong>), which is same as the results in (e), and the small bias shows the reliability of this method.</p>
</font><p><font color="Blue"></font></p>
<p>(g) Based on this data set, provide an estimate for the tenth percentile of medv in Boston census tracts. Call this quantity <span class="math inline">\(\hat \mu_{0.1}\)</span>. (You can use the quantile() function.)</p>
<p>Use the quantile() to estimate the tenth percentile of medv:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(Boston<span class="sc">$</span>medv,<span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  10% 
12.75 </code></pre>
</div>
</div>
<p>(h) Use the bootstrap to estimate the standard error of <span class="math inline">\(\hat \mu_{0.1}\)</span>. Comment on your findings.</p>
<p>Use the same calculation in (c):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>get_quantile_10<span class="ot">&lt;-</span><span class="cf">function</span>(d,i){</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(d[i],<span class="fl">0.1</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>boot_results2<span class="ot">&lt;-</span><span class="fu">boot</span>(Boston<span class="sc">$</span>medv, get_quantile_10, <span class="at">R=</span><span class="dv">10000</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>boot_results2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston$medv, statistic = get_quantile_10, R = 10000)


Bootstrap Statistics :
    original   bias    std. error
t1*    12.75 0.010955   0.5034204</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>boot_sd2<span class="ot">&lt;-</span><span class="fu">sd</span>(boot_results2<span class="sc">$</span>t)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>boot_sd2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5034204</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate 10th percentile</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(boot_results2<span class="sc">$</span>t,<span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  10% 
11.95 </code></pre>
</div>
</div>
<p>As we can see, the std.error is 0.5030691. The estimate 10th percentile is 11.95(<strong>median(boot_results1$t)</strong>), which is slightly different to 12.75. The small bias shows the reliability of this method.</p>
</section>
<section id="least-squares-is-mle-10pts" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-is-mle-10pts">Least squares is MLE (10pts)</h2>
<p>Show that in the case of linear model with Gaussian errors, maximum likelihood and least squares are the same thing, and <span class="math inline">\(C_p\)</span> and AIC are equivalent.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Let’s assume the model is</p>
<p><span class="math display">\[
Y=X\beta +\epsilon,
\]</span></p>
<p>where <span class="math inline">\(Y\)</span> is the vector of observed responses, <span class="math inline">\(X\)</span> is the design matrix, <span class="math inline">\(\beta\)</span> is the vector of unknown coefficients, <span class="math inline">\(\epsilon\)</span> is the vector of Gaussian errors.</p>
<p>So the likelihood function can be expressed as</p>
<p><span class="math display">\[
L(\beta|Y,X)=\frac{1}{(2\pi\sigma^2)^{n/2}}e^{-\frac{1}{2\pi\sigma^2}(Y-X\beta)^\top(Y-X\beta)}
\]</span></p>
<p>where <span class="math inline">\(\sigma^2\)</span> stands for the variance of errors.</p>
<p>Finding the maximum likelihood is equal to find the maximum <span class="math inline">\(L(\beta|Y,X)\)</span>, which is equal to find the minimum of the following part:</p>
<p><span class="math display">\[
(Y-X\beta)^\top(Y-X\beta).
\]</span></p>
<p>And that’s exactly the objective function of least squares method. Thus, maximum likelihood and least squares are the same thing for this situation.</p>
<p><span class="math inline">\(C_p\)</span> and AIC can be expressed as following equations:</p>
<p><span class="math display">\[
C_p=\frac{1}{n}(RSS+2d\hat\sigma^2)
\]</span></p>
<p><span class="math display">\[
AIC=2k-2log(L)
\]</span></p>
<p>In the case of linear regression with Gaussian errors, the likelihood function <span class="math inline">\(L\)</span> is proportional to <span class="math inline">\(e^{-\frac{1}{2}\log(RSS)}\)</span>, which means AIC is proportional to <span class="math inline">\(RSS+2k\)</span>.</p>
<p><span class="math inline">\(k\)</span> in AIC includes the intercept term, whereas in <span class="math inline">\(C_p\)</span>, <span class="math inline">\(d\)</span> only includes the number of predictors. <span class="math inline">\(2k+RSS\)</span> in AIC accounts for the penalty for the number of parameters. So <span class="math inline">\(C_p\)</span> actually is equivalent to <span class="math inline">\(AIC\)</span>, only different in a constant factor.</p>
</font><p><font color="Blue"></font></p>
</section>
<section id="isl-exercise-6.6.1-10pts" class="level2">
<h2 class="anchored" data-anchor-id="isl-exercise-6.6.1-10pts">ISL Exercise 6.6.1 (10pts)</h2>
<p>We perform best subset, forward stepwise, and backward stepwise selection on a single data set. For each approach, we obtain p + 1 models, containing 0, 1, 2, ……, p predictors. Explain your answers:</p>
<p>(a) Which of the three models with k predictors has the smallest training RSS?</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Best subset selection model has the smallest training RSS.</p>
<p>That’s because it is the one selected among all k-predictor-models. In forward stepwise selection, it’s selected from <span class="math inline">\(p-k\)</span> models, while in backwards stepwise, it is selected from <span class="math inline">\(k\)</span> models.</p>
</font><p><font color="Blue"></font></p>
<p>(b) Which of the three models with k predictors has the smallest test RSS?</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>It can’t be determined answer. The best subset selection have higher probability to have the smallest testing RSS since it considered more models, but when the <span class="math inline">\(p\)</span> is relatively large, best subset selection tends to have overfitting problem. Besides, the other 2 selection may simply chose one model that has smaller testing RSS.</p>
</font><p><font color="Blue"></font></p>
<p>(c) True or False:</p>
<ol type="i">
<li><p>The predictors in the k-variable model identified by forward stepwise are a subset of the predictors in the (k+1)-variable model identified by forward stepwise selection.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>True.</p>
</font><p><font color="Blue"></font></p></li>
<li><p>The predictors in the k-variable model identified by backward stepwise are a subset of the predictors in the (k + 1)- variable model identified by backward stepwise selection.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>True.</p>
</font><p><font color="Blue"></font></p></li>
<li><p>The predictors in the k-variable model identified by backward stepwise are a subset of the predictors in the (k + 1)- variable model identified by forward stepwise selection.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>False.</p>
</font><p><font color="Blue"></font></p></li>
<li><p>The predictors in the k-variable model identified by forward stepwise are a subset of the predictors in the (k+1)-variable model identified by backward stepwise selection.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>False.</p>
</font><p><font color="Blue"></font></p></li>
<li><p>The predictors in the k-variable model identified by best subset are a subset of the predictors in the (k + 1)-variable model identified by best subset selection.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>False.</p>
</font><p><font color="Blue"></font></p></li>
</ol>
</section>
<section id="isl-exercise-6.6.3-10pts" class="level2">
<h2 class="anchored" data-anchor-id="isl-exercise-6.6.3-10pts">ISL Exercise 6.6.3 (10pts)</h2>
<p>Suppose we estimate the regression coefficients in a linear regression model by minimizing</p>
<p><span class="math display">\[
\sum_{i=1}^{n}(y_i-\beta_0-\sum_{j=1}^{p}\beta_jx_{ij})^2 \\subject\ to \sum_{j=1}^{p}|\beta_j|\le s
\]</span></p>
<p>for a particular value of s. For parts (a) through (e), indicate which of i. through v. is correct. Justify your answer.</p>
<p>(a) As we increase s from 0, the training RSS will:</p>
<ol type="i">
<li>Increase initially, and then eventually start decreasing in an inverted U shape.</li>
<li>Decrease initially, and then eventually start increasing in a U shape.</li>
<li>Steadily increase.</li>
<li>Steadily decrease.</li>
<li>Remain constant.</li>
</ol>
<p><font color="Blue"></font></p><font color="Blue">
<p>iv., because with the increase of <span class="math inline">\(s\)</span>, the restriction to <span class="math inline">\(\beta_j\)</span> is getting less. That allows the flexibility of the model increasing, leading to the decrease of training RSS.</p>
</font><p><font color="Blue"></font></p>
<p>(b) Repeat (a) for test RSS.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>ii., The first decrease is caused by the increase of model flexibility. Then with a more higher <span class="math inline">\(s\)</span>, there will be overfitting problem, the model will be too fit the training data, causing testing RSS increase.</p>
</font><p><font color="Blue"></font></p>
<p>(c) Repeat (a) for variance.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>iii., the increase of <span class="math inline">\(s\)</span> causes the increase of model flexibility. It will lead to the increase of variance.</p>
</font><p><font color="Blue"></font></p>
<p>(d) Repeat (a) for (squared) bias.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>iv., the increase of <span class="math inline">\(s\)</span> causes the increase of model flexibility. It will lead to the decrease of bias.</p>
</font><p><font color="Blue"></font></p>
<p>(e) Repeat (a) for the irreducible error.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>v., the irreducible error is independant to the model, won’t be affected by the increase of <span class="math inline">\(s\)</span>.</p>
</font><p><font color="Blue"></font></p>
</section>
<section id="isl-exercise-6.6.4-10pts" class="level2">
<h2 class="anchored" data-anchor-id="isl-exercise-6.6.4-10pts">ISL Exercise 6.6.4 (10pts)</h2>
<p>Suppose we estimate the regression coefficients in a linear regression model by minimizing</p>
<p><span class="math display">\[
\sum_{i=1}^{n}(y_i-\beta_0-\sum_{j=1}^{p}\beta_jx_{ij})^2+\lambda\sum_{j=1}^{p}\beta_j^2
\]</span></p>
<p>for a particular value of <span class="math inline">\(\lambda\)</span>. For parts (a) through (e), indicate which of i. through v. is correct. Justify your answer.</p>
<p>(a) As we increase <span class="math inline">\(\lambda\)</span> from 0, the training RSS will:</p>
<ol type="i">
<li>Increase initially, and then eventually start decreasing in an inverted U shape.</li>
<li>Decrease initially, and then eventually start increasing in a U shape.</li>
<li>Steadily increase.</li>
<li>Steadily decrease.</li>
<li>Remain constant.</li>
</ol>
<p><font color="Blue"></font></p><font color="Blue">
<p>iii., because with the increase of <span class="math inline">\(\lambda\)</span>, the restriction to <span class="math inline">\(\beta_j\)</span> is getting more (greater panalty). That makes the flexibility of the model decreasing, leading to the increase of training RSS.</p>
</font><p><font color="Blue"></font></p>
<p>(b) Repeat (a) for test RSS.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>ii., The first decrease is caused by the decrease of model complexity, causing the model less likely to meet overfitting problem. But when the model become too simple as the result of high <span class="math inline">\(\lambda\)</span>, the model will be inapplicable to find the pattern of the data, causing the increase of testing RSS.</p>
</font><p><font color="Blue"></font></p>
<p>(c) Repeat (a) for variance.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>iv., the increase of <span class="math inline">\(\lambda\)</span> causes the decrease of model flexibility. It will lead to the decrease of variance.</p>
</font><p><font color="Blue"></font></p>
<p>(d) Repeat (a) for (squared) bias.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>iii., the increase of <span class="math inline">\(\lambda\)</span> causes the decrease of model flexibility. It will lead to the increase of bias.</p>
</font><p><font color="Blue"></font></p>
<p>(e) Repeat (a) for the irreducible error.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>v., the irreducible error is independant to the model, won’t be affected by the increase of <span class="math inline">\(\lambda\)</span>.</p>
</font><p><font color="Blue"></font></p>
</section>
<section id="isl-exercise-6.6.5-10pts" class="level2">
<h2 class="anchored" data-anchor-id="isl-exercise-6.6.5-10pts">ISL Exercise 6.6.5 (10pts)</h2>
<p>It is well-known that ridge regression tends to give similar coefficient values to correlated variables, whereas the lasso may give different coefficient values to correlated variables. We will now explore this property in a very simple setting.</p>
<p>Suppose that <span class="math inline">\(n\)</span> = 2, <span class="math inline">\(p\)</span> = 2, <span class="math inline">\(x_{11}\)</span> = <span class="math inline">\(x_{12}\)</span>, <span class="math inline">\(x_{21}\)</span> = <span class="math inline">\(x_{22}\)</span>. Furthermore, suppose that <span class="math inline">\(y_1+y_2= 0\)</span> and <span class="math inline">\(x_{11}+x_{21} = 0\)</span> and <span class="math inline">\(x_{12}+x_{22} = 0\)</span> , so that the estimate for the intercept in a least squares, ridge regression, or lasso model is zero: <span class="math inline">\(\hat\beta_0 = 0\)</span>.</p>
<p>(a) Write out the ridge regression optimization problem in this setting.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>We use <span class="math inline">\(x_1\)</span> to express <span class="math inline">\(x_{11}\)</span> and <span class="math inline">\(x_{12}\)</span>, use <span class="math inline">\(x_2\)</span> to express <span class="math inline">\(x_{21}\)</span> and <span class="math inline">\(x_{22}\)</span>,</p>
<p>the problem becomes</p>
<p><span class="math display">\[
\min_{\hat\beta_1,\hat\beta_2}[\sum_{i=1}^{2}(y_i-x_{i}\sum_{j=1}^{2}\hat\beta_j)^2+\lambda\sum_{j=1}^{2}\hat\beta_j^2]
\]</span></p>
</font><p><font color="Blue"></font></p>
<p>(b) Argue that in this setting, the ridge coefficient estimates satisfy <span class="math inline">\(\hat\beta_1=\hat\beta_2\)</span>.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>To minimize formula, we consider finding the derivative:</p>
<p><span class="math display">\[
\frac{\partial }{\partial \hat\beta_1}=(2\hat\beta_1x_{1}^2-2x_{1}y_1+2\hat\beta_2x_{1}^2) + (2\hat\beta_1x_{2}^2-2x_{2}y_2+2\hat\beta_2x_{2}x_{2}) + 2\lambda\hat\beta_1
\]</span></p>
<p>Setting the derivative equal to 0, we have</p>
<p><span class="math display">\[
\hat\beta_1 (x_1^2+x_2^2) + \hat\beta_2 (x_1^2+x_2^2) + \lambda\hat\beta_1 = x_1y_1 + x_2y_2
\]</span></p>
<p>Adding <span class="math inline">\(2x_1x_2\beta_1\)</span> and <span class="math inline">\(2x_1x_2\beta_2\)</span> on the two sides of the equation:</p>
<p><span class="math display">\[
\hat\beta_1 (x_1 + x_2)^2 + \hat\beta_2 (x_1 + x_2)^2 + \lambda\hat\beta_1 = x_1y_1 + x_2y_2 + 2\hat\beta_1x_1x_2 + 2\hat\beta_2x_1x_2
\]</span></p>
<p>So we have</p>
<p><span class="math display">\[
\lambda\hat\beta_1=x_1y_1 + x_2y_2 + 2\hat\beta_1x_1x_2 + 2\hat\beta_2x_1x_2
\]</span></p>
<p>Applying this calculation to <span class="math inline">\(\hat\beta_2\)</span>, we have</p>
<p><span class="math display">\[
\lambda\hat\beta_2=x_1y_1 + x_2y_2 + 2\hat\beta_1x_1x_2 + 2\hat\beta_2x_1x_2
\]</span></p>
<p>So we have <span class="math inline">\(\lambda\hat\beta_1=\lambda\hat\beta_2\)</span>, then <span class="math inline">\(\hat\beta_1=\hat\beta_2\)</span></p>
</font><p><font color="Blue"></font></p>
<p>(c) Write out the lasso optimization problem in this setting.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Using the same transformation in (a), we have</p>
<p><span class="math display">\[
\min_{\hat\beta_1,\hat\beta_2}[\sum_{i=1}^{2}(y_i-x_{i}\sum_{j=1}^{2}\hat\beta_j)^2+\lambda\sum_{j=1}^{2}|\hat\beta_j|]
\]</span></p>
</font><p><font color="Blue"></font></p>
<p>(d) Argue that in this setting, the lasso coefficients <span class="math inline">\(\hat\beta_1\)</span> and <span class="math inline">\(\hat\beta_2\)</span>are not unique——in other words, there are many possible solutions to the optimization problem in (c). Describe these solutions.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>We can apply the same calculation in (b), the absolute value’s derivative is</p>
<p><span class="math display">\[
\frac{\partial }{\partial \hat\beta}=\frac{|\beta|}{\beta}
\]</span></p>
<p>After applying the method in (b), we have</p>
<p><span class="math display">\[
\frac{|\beta_1|}{\beta_1}=\frac{|\beta_2|}{\beta_2}
\]</span></p>
<p>So, <span class="math inline">\(\hat\beta_1\)</span> and <span class="math inline">\(\hat\beta_2\)</span> should have the same positivity (all greater than 0 or all less than 0).</p>
</font><p><font color="Blue"></font></p>
</section>
<section id="isl-exercise-6.6.11-30pts" class="level2">
<h2 class="anchored" data-anchor-id="isl-exercise-6.6.11-30pts">ISL Exercise 6.6.11 (30pts)</h2>
<p>We will now try to predict per capita crime rate in the Boston dataset.</p>
<p><font color="Blue"></font></p><font color="Blue">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Method</th>
<th style="text-align: center;">CV RMSE</th>
<th style="text-align: center;">Test RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">LS</td>
<td style="text-align: center;">not applicable</td>
<td style="text-align: center;">11.63132</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ridge</td>
<td style="text-align: center;">21.53136</td>
<td style="text-align: center;">11.68697</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Lasso</td>
<td style="text-align: center;">21.71989</td>
<td style="text-align: center;">11.63515</td>
</tr>
</tbody>
</table>
</font><p><font color="Blue"></font></p>
<p>(a) Try out some of the regression methods explored in this chapter, such as best subset selection, the lasso, ridge regression, and PCR. Present and discuss results for the approaches that you consider.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>We are going to use 3 methods: least squares, lasso, and ridge.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Boston<span class="sc">$</span>crim,Boston[,<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             zn     indus        chas       nox         rm       age        dis
[1,] -0.2004692 0.4065834 -0.05589158 0.4209717 -0.2192467 0.3527343 -0.3796701
           rad       tax   ptratio     lstat       medv
[1,] 0.6255051 0.5827643 0.2899456 0.4556215 -0.3883046</code></pre>
</div>
</div>
<p>As we can see, the indus, nox, rad, tax, lstat seems have relatively high relation with crim.</p>
<p>So, for each method, we try 3 models: crim ~ rad; crim~[indus, nox, rad, tax, lstat], crim~. .</p>
<p>The 1~400 rows as training data, 401~500 rows as testing data.</p>
<p>LS:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>Boston_train<span class="ot">&lt;-</span>Boston[<span class="dv">1</span><span class="sc">:</span><span class="dv">400</span>,]</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>Boston_test<span class="ot">&lt;-</span>Boston[<span class="dv">401</span><span class="sc">:</span><span class="dv">500</span>,]</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a recipe for data preprocessing</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>norm_recipe <span class="ot">&lt;-</span> </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recipe</span>(</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    crim <span class="sc">~</span> indus <span class="sc">+</span> nox <span class="sc">+</span> rad <span class="sc">+</span> tax <span class="sc">+</span> lstat, </span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Boston_train</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prep</span>(<span class="at">training =</span> Boston_train, <span class="at">retain =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>norm_recipe</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Using ordinary Least Squares</span></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> </span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>(<span class="at">penalty =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span>  <span class="co"># Specifying penalty as 0 means no penalty is applied</span></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)             <span class="co"># Setting the engine to ordinary Least Squares</span></span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a workflow</span></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>lm_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lm_mod) <span class="sc">%&gt;%</span></span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(norm_recipe)</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>lm_wf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow ════════════════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: linear_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
3 Recipe Steps

• step_dummy()
• step_zv()
• step_normalize()

── Model ───────────────────────────────────────────────────────────────────────
Linear Regression Model Specification (regression)

Main Arguments:
  penalty = 0

Computational engine: lm </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting the model</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fit_lm <span class="ot">&lt;-</span> lm_wf <span class="sc">%&gt;%</span> <span class="fu">fit</span>(<span class="at">data =</span> Boston_train)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the results</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>coefficients <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(fit_lm<span class="sc">$</span>fit<span class="sc">$</span>fit)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the coefficient estimates</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coefficients, <span class="fu">aes</span>(<span class="at">x =</span> term, <span class="at">y =</span> estimate)) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Predictors"</span>,</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Coefficient Estimates"</span>,</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Coefficient Estimates from Ordinary Least Squares"</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We have the LS model coefficients results.</p>
<p>Ridge:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>lambda_grid <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">5</span>, <span class="at">length.out =</span> <span class="dv">100</span>))</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>ridge_mod <span class="ot">&lt;-</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>(<span class="at">penalty =</span> <span class="dv">1</span>, <span class="at">mixture =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>, <span class="at">path_values =</span> lambda_grid)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>ridge_mod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression Model Specification (regression)

Main Arguments:
  penalty = 1
  mixture = 0

Engine-Specific Arguments:
  path_values = lambda_grid

Computational engine: glmnet </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>ridge_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(ridge_mod) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(norm_recipe)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>ridge_wf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow ════════════════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: linear_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
3 Recipe Steps

• step_dummy()
• step_zv()
• step_normalize()

── Model ───────────────────────────────────────────────────────────────────────
Linear Regression Model Specification (regression)

Main Arguments:
  penalty = 1
  mixture = 0

Engine-Specific Arguments:
  path_values = lambda_grid

Computational engine: glmnet </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>fit_ridge <span class="ot">&lt;-</span> ridge_wf <span class="sc">%&gt;%</span> <span class="fu">fit</span>(<span class="at">data =</span> Boston_train)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">:::</span><span class="fu">tidy.glmnet</span>(fit_ridge<span class="sc">$</span>fit<span class="sc">$</span>fit<span class="sc">$</span>fit) <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">!=</span> <span class="st">"(Intercept)"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> lambda, <span class="at">y =</span> estimate, <span class="at">color =</span> term)) <span class="sc">+</span> </span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">quote</span>(lambda),</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Standardized Coefficients"</span>,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Ridge solution path for Boston data"</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 606 × 5
   term         step estimate  lambda dev.ratio
   &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)     1     1.75 100000   0.000137
 2 (Intercept)     2     1.75  83022.  0.000165
 3 (Intercept)     3     1.75  68926.  0.000198
 4 (Intercept)     4     1.75  57224.  0.000239
 5 (Intercept)     5     1.75  47508.  0.000287
 6 (Intercept)     6     1.75  39442.  0.000346
 7 (Intercept)     7     1.75  32745.  0.000417
 8 (Intercept)     8     1.75  27186.  0.000502
 9 (Intercept)     9     1.75  22570.  0.000605
10 (Intercept)    10     1.75  18738.  0.000728
# ℹ 596 more rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Transformation introduced infinite values in continuous x-axis</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We now finished the ridge regression. To determine the <span class="math inline">\(\lambda\)</span> value, we can perform cross validation：</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>columns <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(Boston_train, indus, nox, rad, tax, lstat))</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>cv1 <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(columns, Boston_train<span class="sc">$</span>crim, <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">type.measure =</span> <span class="st">"mse"</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>min_error_index1 <span class="ot">&lt;-</span> <span class="fu">which.min</span>(cv1<span class="sc">$</span>cvm)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>best_lambda1 <span class="ot">&lt;-</span> cv1<span class="sc">$</span>lambda[min_error_index1]</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>min_error1 <span class="ot">&lt;-</span> cv1<span class="sc">$</span>cvm[min_error_index1]</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>best_lambda1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3758891</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>min_error1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.78258</code></pre>
</div>
</div>
<p>Then we obtained the best <span class="math inline">\(\lambda\)</span>, as well as the CV MSE.</p>
<p>Lasso:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>lambda_grid <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">100</span>))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>lasso_mod <span class="ot">&lt;-</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>(<span class="at">penalty =</span> <span class="dv">1</span>, <span class="at">mixture =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>, <span class="at">path_values =</span> lambda_grid)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>lasso_mod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression Model Specification (regression)

Main Arguments:
  penalty = 1
  mixture = 1

Engine-Specific Arguments:
  path_values = lambda_grid

Computational engine: glmnet </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>lasso_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lasso_mod) <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(norm_recipe)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>lasso_wf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow ════════════════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: linear_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
3 Recipe Steps

• step_dummy()
• step_zv()
• step_normalize()

── Model ───────────────────────────────────────────────────────────────────────
Linear Regression Model Specification (regression)

Main Arguments:
  penalty = 1
  mixture = 1

Engine-Specific Arguments:
  path_values = lambda_grid

Computational engine: glmnet </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>fit_lasso <span class="ot">&lt;-</span> lasso_wf <span class="sc">%&gt;%</span> <span class="fu">fit</span>(<span class="at">data =</span> Boston_train)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">:::</span><span class="fu">tidy.glmnet</span>(fit_lasso<span class="sc">$</span>fit<span class="sc">$</span>fit<span class="sc">$</span>fit) <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>) <span class="sc">%&gt;%</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">!=</span> <span class="st">"(Intercept)"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> lambda, <span class="at">y =</span> estimate, <span class="at">color =</span> term)) <span class="sc">+</span> </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">quote</span>(lambda), </span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Standardized Coefficients"</span>,</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Lasso solution path for Boston data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 286 × 5
   term         step estimate lambda dev.ratio
   &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)     1     1.75 10000          0
 2 (Intercept)     2     1.75  8498.         0
 3 (Intercept)     3     1.75  7221.         0
 4 (Intercept)     4     1.75  6136.         0
 5 (Intercept)     5     1.75  5214.         0
 6 (Intercept)     6     1.75  4431.         0
 7 (Intercept)     7     1.75  3765.         0
 8 (Intercept)     8     1.75  3199.         0
 9 (Intercept)     9     1.75  2719.         0
10 (Intercept)    10     1.75  2310.         0
# ℹ 276 more rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Transformation introduced infinite values in continuous x-axis</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We now finished the lassoregression. To determine the <span class="math inline">\(\lambda\)</span> value, we can perform cross validation：</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>columns <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(Boston_train, indus, nox, rad, tax, lstat))</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>cv2 <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(columns, Boston_train<span class="sc">$</span>crim, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">type.measure =</span> <span class="st">"mse"</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>min_error_index2 <span class="ot">&lt;-</span> <span class="fu">which.min</span>(cv2<span class="sc">$</span>cvm)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>best_lambda2 <span class="ot">&lt;-</span> cv2<span class="sc">$</span>lambda[min_error_index2]</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>min_error2 <span class="ot">&lt;-</span> cv2<span class="sc">$</span>cvm[min_error_index2]</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>best_lambda2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0205321</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>min_error2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.4826</code></pre>
</div>
</div>
<p>Then we obtained the best <span class="math inline">\(\lambda\)</span>, as well as the CV MSE.</p>
</font><p><font color="Blue"></font></p>
<p>(b) Propose a model (or set of models) that seem to perform well on this data set, and justify your answer. Make sure that you are evaluating model performance using validation set error, crossvalidation, or some other reasonable alternative, as opposed to using training error.</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>Let’s calculate the Test RMSE for the 3 methods.</p>
<p>LS:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_lm, <span class="at">new_data =</span> Boston_test)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>test_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(<span class="fu">unlist</span>((Boston_test<span class="sc">$</span>crim <span class="sc">-</span> predictions)<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>test_rmse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.63132</code></pre>
</div>
</div>
<p>Ridge:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>columns <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(Boston_test, indus, nox, rad, tax, lstat))</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(cv1, <span class="at">newx =</span> columns,<span class="at">s=</span>best_lambda1)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>test_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(<span class="fu">unlist</span>((Boston_test<span class="sc">$</span>crim <span class="sc">-</span> predictions)<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>test_rmse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.68697</code></pre>
</div>
</div>
<p>Lasso:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>columns <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(Boston_test, indus, nox, rad, tax, lstat))</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(cv2, <span class="at">newx =</span> columns,<span class="at">s=</span>best_lambda2)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>test_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(<span class="fu">unlist</span>((Boston_test<span class="sc">$</span>crim <span class="sc">-</span> predictions)<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>test_rmse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.63848</code></pre>
</div>
</div>
</font><p><font color="Blue"></font></p>
<p>(c) Does your chosen model involve all of the features in the data set? Why or why not?</p>
<p><font color="Blue"></font></p><font color="Blue">
<p>No, some features have very little relationship to crim, involving those features can reduce model accuracy.</p>
</font><p><font color="Blue"></font></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>